# Generated by Django 2.0.3 on 2018-03-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumReg', models.IntegerField()),
                ('Nombre', models.CharField(max_length=100)),
                ('ApellidoP', models.CharField(max_length=100)),
                ('ApellidoM', models.CharField(max_length=100)),
                ('CorreoE', models.CharField(max_length=200)),
                ('FechaReg', models.DateField()),
                ('Activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='miembro',
            unique_together={('CorreoE',)},
        ),
    ]
