# Generated by Django 2.0.3 on 2018-03-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miembro',
            name='id',
        ),
        migrations.AlterField(
            model_name='miembro',
            name='NumReg',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
