# Generated by Django 2.0.3 on 2018-03-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20180326_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='Campo1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='miembro',
            name='Campo2',
            field=models.CharField(default='', max_length=200),
        ),
    ]
